# Generated by Django 6.0.7 on 2026-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
